# Generated by Django 4.2.7 on 2023-12-10 16:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="ubication",
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="video_url",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
